import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import UserInitializer from "@/components/userInitializer";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserInitializer />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
